<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>UCI File Generate </TITLE>
</HEAD>
<BODY  bgcolor="#FFFFCC" TOPMARGIN="0">
<CFPARAM NAME="chkval" DEFAULT="">
<CFPARAM NAME="frdate" DEFAULT="">
<CFPARAM NAME="todate" DEFAULT="">
<CFPARAM NAME="market" DEFAULT="">
<CFPARAM NAME="batchNo" DEFAULT="">
<CFPARAM NAME="chkClient" DEFAULT="Trd">
<CFOUTPUT>
<CFSET chkval="#Left(chkval,(Len(chkval)-1))#">
	
<cfquery name="GetName" datasource="#Client.database#">
	select ltrim(rtrim(CHEKERUSERLIST)) CHEKERUSERLIST
		from system_settings
	where company_code = '#cocd#'
</cfquery>

<CFQUERY NAME="GetClientDetails" datasource="#Client.database#">
	SELECT DISTINCT  A.CLIENT_ID, pan_name CLIENT_NAME,B.MARKET,A.COMPANY_CODE,A.REGISTRATION_DATE,A.LAST_MODIFIED_DATE,
		B.MAPIN,B.PAN_NO,B.PASSPORT_NO,CONVERT(VARCHAR(11),B.PASSPORT_EXPIRY_DATE,106) PASSPORT_EXPIRY_DATE,CONVERT(VARCHAR(11),PASS_ISSUE_DATE,106) PASS_ISSUE_DATE1,
		PASSPORT_ISSUED_PLACE,
		RESI_FAX_NO,ISNULL(STD_Code,'0') STD_Code,CONVERT(VARCHAR(11),dr_lic_exp_date,106) dr_lic_exp_date,
		DRIVING_LICENSE,CONVERT(VARCHAR(11),DRIVING_LICENSE_ISSUED_DATE,106) DRIVING_LICENSE_ISSUED_DATE1,DRIVING_LICENSE_ISSUED_PLACE,
		VOTERS_ID_CARD, CONVERT(VARCHAR(11),VOTERS_ID_CARD_ISSUED_DATE,106) VOTERS_ID_CARD_ISSUED_DATE1,Place_Issue_Vouter_ID,
		RATIONCARD,RATIONCARD_ISSUED_PLACE,CONVERT(VARCHAR(11),RATIONCARD_expiry_DATE,106) RATIONCARD_expiry_DATE1,
		A.LAST_NAME + '' + A.FIRST_NAME+''+A.MIDDLE_NAME CLIENTFULLNAME,
		isnull(B.CATEGORY,'')CATEGORY,REG_ADDR RESI_ADDRESS,R_PIN_CODE PIN_CODE,R_STATE,R_COUNTRY,R_CITY,
		RESI_TEL_NO,CONVERT(VARCHAR(11),BIRTH_DATE,106) BIRTH_DATE1,
		INTR_LAST_NAME + '' + INTR_FIRST_NAME +''+INTR_MIDDLE_NAME INTRFULLNAME,ISNULL(INTRODUCER_NAME,'')INTRODUCER_NAME,
		REL_WITH_INTRODUCER,INTRODUCER_ACC_CODE ,Registration_Number,Registration_Authority,Place_Of_Reg,Convert(Varchar(11),Date_of_Reg,106)  Date_of_Reg,
			Convert(Varchar(11),A.REGISTRATION_DATE,106) REGISTRATION_DATE,Convert(Varchar(11),AGREEMENT_DATE,106)  AGREEMENT_DATE,
			A.First_Name,A.Middle_Name,A.Last_Name,UIN,
			ISNULL(PAN_NAME,A.CLIENT_NAME) PAN_NAME,
			ISNULL(SEX,'N') GENDER	,ISNULL(MOBILE_NO,'') MOBILE_NO,
			CLIENT_ID_MAIL
		FROM CLIENT_MASTER A LEFT OUTER JOIN CLIENT_DETAIL_VIEW B
		ON  
			A.CLIENT_ID=B.CLIENT_ID
		AND A.COMPANY_CODE=B.COMPANY_CODE
		LEFT OUTER JOIN COMPANY_MASTER C 
		ON
			A.COMPANY_CODE=C.COMPANY_CODE
		WHERE 
			A.COMPANY_CODE IN(SELECT COMPANY_CODE FROM COMPANY_MASTER WHERE EXCHANGE='NSE' AND FLG_NCX IN ('MCX','NCDX','ICEX'))  
		AND A.COMPANY_CODE = '#COCD#'		
		<CFIF IsDefined('frdate') and IsDefined('todate')>
			AND (
				CONVERT(DATETIME, CONVERT(VarChar(10), A.LAST_MODIFIED_DATE, 103), 103) BETWEEN CONVERT(DATETIME,'#frdate#',103) 
				and CONVERT(DATETIME,'#todate#',103) 
				OR  CONVERT(DATETIME, CONVERT(VarChar(10), A.REGISTRATION_DATE, 103), 103) BETWEEN CONVERT(DATETIME,'#frdate#',103) 
				and CONVERT(DATETIME,'#todate#',103) 
				)
		</CFIF>
		and A.Client_Id in(#PreserveSingleQuotes(chkval)#)
		and isnull(B.CATEGORY,'')!=''
		and (isnull(RTRIM(LTRIM(A.LAST_NAME + '' + A.FIRST_NAME+''+A.MIDDLE_NAME)),'') !='' or isnull(A.CLIENT_NAME,'')!='')
		and LTRIM(RTRIM(RESI_ADDRESS)) !=''
		<cfif len(ltrim(rtrim(GetName.CHEKERUSERLIST))) neq 0>
			AND ISNULL(A.CHEKING,'N') = 'Y'
		</cfif>		
		<CFIF IsDefined('chkClient') and chkClient eq 'Trd'>
		and A.CLIENT_ID IN(SELECT DISTINCT CLIENT_ID FROM TRADE1 WHERE COMPANY_CODE=A.COMPANY_CODE
			AND CONVERT(DATETIME,TRADE_DATE,103)  BETWEEN CONVERT(DATETIME,'#frdate#',103) 
			and CONVERT(DATETIME,'#todate#',103)) 			
		</CFIF>			
 		ORDER BY  A.CLIENT_ID,A.CLIENT_NAME,B.MARKET
</CFQUERY>

<CFIF GetClientDetails.recordcount eq 0>
	<SCRIPT>
		alert("No Data Found");
	</SCRIPT>
	<CFABORT>
</CFIF>

<CFQUERY NAME="GETTRADINGCODE" datasource="#Client.database#">
	SELECT WEBX_ID BROKER_CODE  FROM  COMPANY_MASTER 
	WHERE 
		company_code='#cocd#'
</CFQUERY>

<CFIF not directoryexists("C:\COMMUCC\")>
	<CFDIRECTORY ACTION="CREATE" DIRECTORY="C:\COMMUCC\">
</CFIF>

<SCRIPT LANGUAGE="VBScript">
	newfolderpath = "c:\COMMUCC" 
	Set FileSys = CreateObject("Scripting.FileSystemObject")
	If Not filesys.FolderExists(newfolderpath) Then 
		 Set newfolder = filesys.CreateFolder(newfolderpath) 
	End If
</SCRIPT>

<CFSET FILENAME = "C:\COMMUCC\ICEX_#DateFormat(Now(),"DDMMYYYY")#_UCC#GETTRADINGCODE.BROKER_CODE#.M#batchNo#">
<CFSET FILENAMELOG = "C:\COMMUCC\LOG_ICEX_#DateFormat(Now(),"DDMMYYYY")#_UCC#GETTRADINGCODE.BROKER_CODE#.M#batchNo#">

<CFIF FileExists('#FILENAME#')>
	<CFFILE  ACTION="DELETE" FILE="#FILENAME#"> 
</CFIF>
<CFIF FileExists('#FILENAMELOG#')>
	<CFFILE  ACTION="DELETE" FILE="#FILENAMELOG#"> 
</CFIF>

<CFSET DELIMINATOR = ",">

<CFFILE ACTION="APPEND" FILE="#FILENAME#" OUTPUT="" ADDNEWLINE="NO">
<CFFILE ACTION="APPEND" FILE="#FILENAME#" OUTPUT="0#DELIMINATOR##DateFormat(Now(),'DD.MM.YYYY')##DELIMINATOR##getClientDetails.RECORDCOUNT##DELIMINATOR##GETTRADINGCODE.BROKER_CODE##CHR(10)#" ADDNEWLINE="NO">

<CFSET FINALSTRING = "">
<CFSET FINALSTRINGLOG = "">

<CFIF market eq "CAPS">
	<CFSET SEGMENT = "C">
<CFELSE>
	<CFSET SEGMENT = "F">
</CFIF>
<CFSET MissingBankDetails="Missing Bank Details For Clients :">
<CFSET MissingBankFLG=false>

<CFLOOP QUERY="getClientDetails">
	<CFQUERY NAME="GetclientDpDetails" datasource="#Client.database#">
		Select top 1 DEPOSITORY,DP_ID,CLIENT_DP_CODE,DP_NAME
		FROM IO_DP_MASTER
		WHERE
			CLIENT_ID = '#getClientDetails.CLIENT_ID#'
		ORDER BY  DEFAULT_ACC DESC
	</CFQUERY>
	
	<CFQUERY NAME="GETBANKDETAILS" datasource="#Client.database#">
		SELECT top 1 Bank_Name,Bank_Address,Micr_Code,Bank_AcNo,ACC_OPEN_DATE,
			   BANK_ACCTYPE
		FROM  FA_CLIENT_BANK_DETAILS 
		Where
			Account_Code = '#getClientDetails.Client_id#'
		order by Default_Ac desc 
	</CFQUERY>
	
	<!--- <CFIF GETBANKDETAILS.RECORDCOUNT EQ 0>
		<CFSET MissingBankDetails="#MissingBankDetails##CLIENT_ID#,">
		<CFSET MissingBankFLG=true>
	</CFIF>  GETBANKDETAILS.recordcount neq 0 and GetclientDpDetails.recordcount neq 0 and--->
	<cfset ERRORCODE = 0 >
	<CFIF  len(GetClientDetails.PAN_NO) Neq 10>
		<cfset ERRORCODE = 1 >
	</CFIF>				
				<CFSET CLIENTID						=		'#CLIENT_ID#'>
				<CFSET MAPIN1 						= 		"#LEFT(TRIM(GetClientDetails.MAPIN),9)#">
				<CFSET PAN_NO1 						= 		"#LEFT(TRIM(GetClientDetails.PAN_NO),10)#">
				<CFSET WARDNO						=		"">
				<CFSET PASSPORT_NO1 				=		"#LEFT(TRIM(GetClientDetails.PASSPORT_NO),25)#">
				<CFSET PASSPORT_ISSUED_PLACE1		= 		"#LEFT(TRIM(GetClientDetails.PASSPORT_ISSUED_PLACE),25)#">
				<CFSET Pass_Issue_Date				=		"#Dateformat(GetClientDetails.Pass_Issue_Date1,'DD.MM.YYYY')#">
				<CFSET Pass_Exp_Date				=		"#Dateformat(GetClientDetails.PASSPORT_EXPIRY_DATE,'DD.MM.YYYY')#">
				<CFSET DRIVING_LICENSE1				=		"#LEFT(TRIM(GetClientDetails.DRIVING_LICENSE),25)#">
				<CFSET DRIVING_LICENSE_ISSUED_PLACE1= 		"#LEFT(TRIM(GetClientDetails.DRIVING_LICENSE_ISSUED_PLACE),25)#">
				<CFSET dr_lic_exp_date1				= 		"#Dateformat(GetClientDetails.dr_lic_exp_date,"DD.MM.YYYY")#">
				<CFSET DRIVING_LICENSE_ISSUED_DATE	= 		"#Dateformat(GetClientDetails.DRIVING_LICENSE_ISSUED_DATE1,"DD.MM.YYYY")#">
				<CFSET VOTERS_ID_CARD1				=	 	"#LEFT(TRIM(GetClientDetails.VOTERS_ID_CARD),25)#">
				<CFSET Place_Issue_Vouter_ID1 		= 		"#LEFT(TRIM(GetClientDetails.Place_Issue_Vouter_ID),25)#">
				<CFSET VOTERS_ID_CARD_ISSUED_DATE 	= 		"#Dateformat(GetClientDetails.VOTERS_ID_CARD_ISSUED_DATE1,"DD.MM.YYYY")#">
				<CFSET RATIONCARD1 					=		"#LEFT(TRIM(GetClientDetails.RATIONCARD),25)#">
				<CFSET RATIONCARD_ISSUED_PLACE1		=		"#LEFT(TRIM(GetClientDetails.RATIONCARD_ISSUED_PLACE),25)#">
				<CFSET RATIONCARD_EXPIRY_DATE 		=		"#DATEFORMAT(GetClientDetails.RATIONCARD_EXPIRY_DATE1,"DD.MM.YYYY")#">
				<CFSET REGISTRATION_NO				=		"#LEFT(TRIM(GetClientDetails.Registration_Number),25)#">
				<CFSET REGISTRATION_AUTHORITY		=		"#LEFT(TRIM(GetClientDetails.Registration_Authority),60)#">
				<CFSET REGISTRATION_PLACE 			=		"#LEFT(TRIM(GetClientDetails.Place_Of_Reg),25)#">
				<CFSET REGISTRATION_DATE1			=		"#TRIM(DATEFORMAT(GetClientDetails.Date_of_Reg,"DD.MM.YYYY"))#">
				<CFSET CLIENT_NAME1				=		"#TRIM(GetClientDetails.PAN_NAME)#">
				<CFSET GENDER1				=		"#TRIM(GetClientDetails.GENDER)#">
				<CFSET MOBILE_NO1				=		"#TRIM(GetClientDetails.MOBILE_NO)#">
				<CFSET RESI_FAX_NO1				=		"#TRIM(GetClientDetails.RESI_FAX_NO)#">
				<CFSET CLIENT_ID_MAIL				=		"#TRIM(GetClientDetails.CLIENT_ID_MAIL)#">
				
				<cfif trim(category) eq "I" OR trim(category) eq "NRI">
					<CFSET LASTNAME = "#left(TRIM(GetClientDetails.LAST_NAME),100)#">
					<CFSET FIRSTNAME = "#left(TRIM(GetClientDetails.FIRST_NAME),20)#">
					<CFSET MIDDLENAME = "#left(TRIM(GetClientDetails.MIDDLE_NAME),20)#">
				<CFELSE>
					<CFSET LASTNAME = "">
					<CFSET FIRSTNAME = "">
					<CFSET MIDDLENAME = "">
				</CFIF>	
				
				<!--- <CFIF TRIM(GetClientDetails.PAN_NAME) eq ''>
					<CFSET CLIENT_NAME				=		"#GetClientDetails.client_name#">
				</CFIF> --->
				
				<CFSET CATEGORY1					=		"">
				
				<CFIF GetClientDetails.CATEGORY EQ 'I'>
					<CFSET CATEGORY1				=		"01">
				<CFELSEIF 	GetClientDetails.CATEGORY EQ 'MF'>
					<CFSET CATEGORY1				=		"06">
				<CFELSEIF 	GetClientDetails.CATEGORY EQ 'CO'>
					<CFSET CATEGORY1				=		"13">	
				<CFELSEIF 	GetClientDetails.CATEGORY EQ 'NT'>
					<CFSET CATEGORY1				=		"14">
				<CFELSE>
					<CFSET CATEGORY1				=		"99">		
				</CFIF>
				
				<CFSET Add1="#GetToken(GetClientDetails.RESI_ADDRESS,1,'~')#">
				<CFSET Add2="#GetToken(GetClientDetails.RESI_ADDRESS,2,'~')#">
				<CFSET Add3="#GetToken(GetClientDetails.RESI_ADDRESS,3,'~')#">
				
				<CFSET RESI_ADDRESS1	 			= 	"#Add1##Add2##GetToken(Add3,1,'-')#">
				<!--- <CFIF RESI_ADDRESS1 eq "">
					<CFSET RESI_ADDRESS1			= 	"#REPLACE(GetClientDetails.RESI_ADDRESS,'~',' ','ALL')#">
				</CFIF>
				  --->
				  
				<CFSET PINCODE		 				= 	"#GetClientDetails.Pin_Code#">	
				<CFSET RESI_TEL_NO1	 				= 	"#STD_Code##TRIM(LEFT(GetClientDetails.RESI_TEL_NO,22))#">
				
				<CFIF TRIM(Category) eq "I">
					<CFSET BIRTHDATE	 				= 	"#DateFormat(GetClientDetails.BIRTH_DATE1,'DD.MM.YYYY')#">
				<CFELSE>
					<CFSET BIRTHDATE	 				= 	"">
				</CFIF>
			
				<CFIF LEN(GetClientDetails.AGREEMENT_DATE) GT 0>
					<CFSET AGREEMENT_DATE1			 	= 	"#DATEFORMAT(GetClientDetails.AGREEMENT_DATE,"DD.MM.YYYY")#">	
				<CFELSE>					
					<CFSET AGREEMENT_DATE1			 	= 	"#DATEFORMAT(GetClientDetails.REGISTRATION_DATE,"DD.MM.YYYY")#">		
				</CFIF>
				
				<CFSET INTRODUCER_NAME = "#Trim(GetClientDetails.INTRODUCER_NAME)#">
				<CFSET RELWITHINT		= "">
				<CFSET INTRODUCER_ACC_CODE = "">				
							
				<CFSET Bank_name				= 	"#LEFT(TRIM(GETBANKDETAILS.Bank_Name),60)#">
				<CFSET Bank_Add					= 	"#LEFT(TRIM(GETBANKDETAILS.Bank_Address),225)#">
				<CFSET TYPE						=	"#TRIM(GETBANKDETAILS.BANK_ACCTYPE)#">
				
				<CFIF TYPE EQ "SAVING">
					<CFSET BANKTYPE 			= 	10>
				<CFELSEIF TYPE EQ "CURRENT">
					<CFSET BANKTYPE 			= 	11>
				<CFELSE>
					<CFSET BANKTYPE 			= 	10>
				</CFIF>
				
				<CFSET CLIENTBANKCODE 			= 	"#LEFT(TRIM(GETBANKDETAILS.Bank_AcNo),25)#">
				
				<CFSET DP_ID1					=	"#LEFT(TRIM(GetclientDpDetails.DP_ID),25)#">
				<CFSET DEPOSITORY1				=	"#LEFT(TRIM(GetclientDpDetails.DEPOSITORY),4)#">
				<CFSET CLIENT_DP_CODE1 			= 	"#LEFT(TRIM(GetclientDpDetails.CLIENT_DP_CODE),16)#">
				<CFSET DP_NAME1 				= 	"#TRIM(GetclientDpDetails.DP_NAME)#">
				
				<CFSET OTHERACCOUNT				=	"">
				<CFSET SETTLEMENTMODE			=	"">
				<CFSET CLIENTOTH				=	"">
				<CFSET FLAG						=	"E">
				<CFSET FINALSTRING = "#FINALSTRING#">
				<CFIF LEN(MAPIN) NEQ 9 >
					<CFSET MAPIN="">
				</CFIF>
				
				<!--- <cfquery name="GETRESSTATECODE" datasource="#CLIENT.DATABASE#">
					SELECT *
					FROM STATE_MASTER
					WHERE
						STATE_CODE = '#R_STATE#'
				</cfquery> --->
				<CFSET RESSTATECODE = "91">


				<!--- #DELIMINATOR# --->
				<CFIF TRIM(RESI_TEL_NO1) EQ "">
					<cfset ERRORCODE = 2 >	
				</CFIF>
				
				<CFIF TRIM(MOBILE_NO1) EQ "">
					<cfset ERRORCODE = 3 >	
				</CFIF>
				
				<CFIF TRIM(BIRTHDATE) EQ "">
					<cfset ERRORCODE = 4 >	
				</CFIF>
				
				
				<CFSET FINALSTRING = "#FINALSTRING#1#DELIMINATOR##UCASE(CLIENTID)##DELIMINATOR##UCASE(PAN_NO1)##DELIMINATOR##UCASE(CATEGORY1)##DELIMINATOR##GENDER1##DELIMINATOR##DELIMINATOR##UCASE(FIRSTNAME)##DELIMINATOR##UCASE(LASTNAME)##DELIMINATOR##DELIMINATOR##BIRTHDATE##DELIMINATOR#IN#DELIMINATOR##DELIMINATOR##AGREEMENT_DATE1##DELIMINATOR#C#DELIMINATOR##DELIMINATOR##DELIMINATOR#Default#DELIMINATOR##LEFT(TRIM(REPLACE(UCASE(Add1),',',' ','ALL')),30)##DELIMINATOR##LEFT(TRIM(REPLACE(UCASE(Add2),',',' ','ALL')),30)##DELIMINATOR##LEFT(TRIM(REPLACE(UCASE(Add3),',',' ','ALL')),30)##DELIMINATOR##UCASE(R_CITY)##DELIMINATOR##UCASE(R_COUNTRY)##DELIMINATOR##UCASE(R_STATE)##DELIMINATOR##UCASE(PIN_CODE)##DELIMINATOR##RESSTATECODE##DELIMINATOR##Replace(REPLACE(RESI_TEL_NO1,',',' ','ALL'),'-','','All')##DELIMINATOR##UCASE(MOBILE_NO1)##DELIMINATOR##Replace(REPLACE(RESI_FAX_NO1,',',' ','ALL'),'-','','All')##DELIMINATOR##CLIENT_ID_MAIL##DELIMINATOR#">
				
				
				<!--- <CFIF Bank_Name NEQ "" AND Bank_Add NEQ "" AND CLIENTBANKCODE NEQ "" >
					<CFSET FINALSTRING = "#FINALSTRING##REPLACE(UCASE(Bank_name),',','','ALL')#,#REPLACE(UCASE(Bank_Add),',','','ALL')#,#UCASE(CLIENTBANKCODE)#,#BANKTYPE#,">	
				<CFELSE> --->
					<CFSET FINALSTRING = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR#INR#DELIMINATOR#">
<!--- 				</CFIF> --->
				
				<!--- <CFSET FINALSTRING = "#FINALSTRING#,,,,,,,,"> --->
				
				<!--- <CFIF DEPOSITORY1 EQ "NSDL">
					<CFIF  DP_ID1 NEQ "" AND DEPOSITORY1 NEQ "" AND CLIENT_DP_CODE1 NEQ "" >
						<CFSET FINALSTRING = "#FINALSTRING##UCASE(DEPOSITORY1)#,#DP_ID1#,#UCASE(DP_NAME1)#,#CLIENT_DP_CODE1#,,,,,,">	
					<CFELSE>
						<CFSET FINALSTRING = "#FINALSTRING#,,,,,,,,,">
					</CFIF>
				<cfelse>
					<CFIF  DP_ID1 NEQ "" AND DEPOSITORY1 NEQ "" AND CLIENT_DP_CODE1 NEQ "" >
						<CFSET FINALSTRING = "#FINALSTRING#,,,,,#DEPOSITORY1#,#DP_ID1#,#UCASE(DP_NAME1)#,#CLIENT_DP_CODE1#,">	
					<CFELSE>
						<CFSET FINALSTRING = "#FINALSTRING#,,,,,,,,,">
					</CFIF>	
				</CFIF> --->
				
				<CFIF DRIVING_LICENSE1 NEQ "" AND DRIVING_LICENSE_ISSUED_PLACE1 NEQ "" AND DRIVING_LICENSE_ISSUED_DATE NEQ "" AND dr_lic_exp_date1 NEQ "">
					<CFSET FINALSTRING = "#FINALSTRING##UCASE(DRIVING_LICENSE1)##DELIMINATOR##REPLACE(UCASE(DRIVING_LICENSE_ISSUED_PLACE1),',',' ','ALL')##DELIMINATOR##DRIVING_LICENSE_ISSUED_DATE##DELIMINATOR##dr_lic_exp_date1##DELIMINATOR#">
				<CFELSE>
					<CFSET FINALSTRING = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR##DELIMINATOR#">	
				</CFIF>
				
				<!--- <CFIF VOTERS_ID_CARD1 NEQ "" AND Place_Issue_Vouter_ID1 NEQ "" AND VOTERS_ID_CARD_ISSUED_DATE NEQ "">
					<CFSET FINALSTRING = "#FINALSTRING##UCASE(VOTERS_ID_CARD1)##DELIMINATOR##REPLACE(UCASE(Place_Issue_Vouter_ID1),',',' ','ALL')##DELIMINATOR##VOTERS_ID_CARD_ISSUED_DATE##DELIMINATOR##DELIMINATOR#">
				<CFELSE> --->
					<CFSET FINALSTRING = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR##DELIMINATOR#">	
				<!--- </CFIF> --->

				<CFIF RATIONCARD1 NEQ "" AND RATIONCARD_ISSUED_PLACE1 NEQ "" AND RATIONCARD_EXPIRY_DATE NEQ "">
					<CFSET FINALSTRING = "#FINALSTRING##UCASE(RATIONCARD1)##DELIMINATOR##REPLACE(UCASE(RATIONCARD_ISSUED_PLACE1),',',' ','ALL')##DELIMINATOR##RATIONCARD_EXPIRY_DATE##DELIMINATOR#">
				<CFELSE>
					<CFSET FINALSTRING = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR#">	
				</CFIF>

				<CFIF PASSPORT_NO1 NEQ "" AND PASSPORT_ISSUED_PLACE NEQ "" AND Pass_Issue_Date NEQ "" and Pass_Exp_Date neq "">
					<CFSET FINALSTRING = "#FINALSTRING##UCASE(PASSPORT_NO1)##DELIMINATOR##REPLACE(UCASE(PASSPORT_ISSUED_PLACE1),',','','ALL')##DELIMINATOR##Pass_Issue_Date##DELIMINATOR##Pass_Exp_Date##DELIMINATOR#">
				<CFELSE>
					<CFSET FINALSTRING = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR##DELIMINATOR#">	
				</CFIF>
				
				<CFIF GetClientDetails.CATEGORY NEQ 'I' AND REGISTRATION_NO NEQ "" AND REGISTRATION_AUTHORITY NEQ "" AND REGISTRATION_PLACE NEQ "" AND REGISTRATION_DATE1 NEQ "">
					<CFSET FINALSTRING	   = "#FINALSTRING##UCASE(REGISTRATION_AUTHORITY)##DELIMINATOR##UCASE(REGISTRATION_NO)##DELIMINATOR##UCASE(REGISTRATION_PLACE)##DELIMINATOR##REGISTRATION_DATE1##DELIMINATOR#">
				<CFELSE>
					<CFSET FINALSTRING	   = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR##DELIMINATOR#">
				</CFIF>
				
				<CFSET FINALSTRING	   = "#FINALSTRING##INTRODUCER_NAME##DELIMINATOR##INTRODUCER_ACC_CODE##DELIMINATOR##RELWITHINT##DELIMINATOR##DELIMINATOR#N#DELIMINATOR#">
				
				<CFIF  DP_ID1 NEQ "" AND DEPOSITORY1 NEQ "" AND CLIENT_DP_CODE1 NEQ "" >
					<CFSET FINALSTRING = "#FINALSTRING##DEPOSITORY1##DELIMINATOR##DP_ID1##DELIMINATOR##DP_NAME1##DELIMINATOR##CLIENT_DP_CODE1##CHR(10)#">	
				<CFELSE>
					<CFSET FINALSTRING = "#FINALSTRING##DELIMINATOR##DELIMINATOR##DELIMINATOR##CHR(10)#">
				</CFIF>
							
				<!--- <CFSET FINALSTRING = "#FINALSTRING##CHR(10)#">
				<CFSET FINALSTRINGLOG = "#FINALSTRINGLOG##CLIENT_ID# SuccesFully Generated#chr(10)#"> --->
				<CFIF ERRORCODE EQ 1>
					<CFSET FINALSTRINGLOG = "For #CLIENT_ID# : Insert Proper Pan NO.#chr(10)#">
				<cfelseif ERRORCODE EQ 2>
					<CFSET FINALSTRINGLOG = "For #CLIENT_ID# : Tele Phone is Missing / Length is Not Proper.#chr(10)#">
				<cfelseif ERRORCODE EQ 3>
					<CFSET FINALSTRINGLOG = "For #CLIENT_ID# : Mobile NO. is Missing/ Length is Not Proper.#chr(10)#">
				<cfelseif ERRORCODE EQ 4>
					<CFSET FINALSTRINGLOG = "For #CLIENT_ID# : Birth Date / Date of Incorporation is Missing.#chr(10)#">	
				<cfelse>
					<CFSET FINALSTRINGLOG = "For #CLIENT_ID# : Generated SucessFully.#chr(10)#">		
				</CFIF>
				
				<cfif len(FINALSTRINGLOG) gt 0>
					<CFFILE ACTION="APPEND" FILE="#FILENAMELOG#" OUTPUT="#FINALSTRINGLOG#" ADDNEWLINE="Yes">
				</cfif>
				
				<cfif ERRORCODE EQ 0 and len(FINALSTRING) gt 0>
					<CFFILE ACTION="APPEND" FILE="#FILENAME#" OUTPUT="#FINALSTRING#" ADDNEWLINE="No">		
				</cfif>
				
				<cfset FINALSTRINGLOG = "">
				<cfset FINALSTRING = "">
		<!--- <CFELSE>
			<CFSET FINALSTRINGLOG = "#FINALSTRINGLOG#For #CLIENT_ID# Pan No is Missing#chr(10)#">
		</CFIF>  --->
	</CFLOOP>
<!--- <CFIF Trim(MissingBankFLG) eq true>
	<SCRIPT>
		alert("#MissingBankDetails#");
	</SCRIPT>
	<CFABORT>
</CFIF> --->
<!--- <CFFILE ACTION="APPEND" FILE="#FILENAME#" OUTPUT="#FINALSTRING#" ADDNEWLINE="no">
<CFFILE ACTION="APPEND" FILE="#FILENAMELOG#" OUTPUT="#FINALSTRINGLOG#" ADDNEWLINE="no">
 --->
<CFINCLUDE TEMPLATE="../../Common/CopyFile.cfc">


<CFSET	ClientFileGenerated	=	CopyFile("#FileName#","#FileName#")>
<CFSET	ClientFileGenerated1	=	CopyFile("#FILENAMELOG#","#FILENAMELOG#")>

<CFIF  ClientFileGenerated>
	<SCRIPT>
		alert("File Generated On Client Machine #REPLACE(FILENAME,'\','\\','ALL')#");
	</SCRIPT>
</CFIF>
			
<CFIF ClientFileGenerated1>
	<SCRIPT>
		alert("Log File Generated on Client Machine #REPLACE(FILENAMELOG,'\','\\','ALL')#");
	</SCRIPT>
</CFIF>

FILE GENERATED On Your <A target="blank" HREF="FILE:\\#Server_NAme#\#Replace(FileName,":","")#">#FILENAME#.
</CFOUTPUT>
</BODY>
</HTML>
